blogs_list = {
    'en': [
        {
            'slug': 'how-to-convert-image-from-jpeg-to-jpg',
            'title': 'How to convert JPEG to JPG free online',
            'description': 'How to convert your JPEG images to JPG format for free online',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-blur-face-on-images-online-for-free',
            'title': 'How to apply blur filter on face in images',
            'description': 'Discover how to apply blur effect on the face in images online for free',
            'image': 'blur-face-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-jpeg',
            'title': 'How to convert bitmap/bmp to JPEG free online',
            'description': 'How to convert your bitmap images to JPEG format for free online',
            'image': 'bitmap-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-tiff',
            'title': 'How to convert webp to tiff free online',
            'description': 'How to convert your webp images to tiff format for free online',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-jpeg',
            'title': 'How to convert webp to jpeg free online',
            'description': 'How to convert your webp images to jpeg format for free online',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-png',
            'title': 'How to convert bmp to png free online',
            'description': 'How to convert your bmp images to png format for free online',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-png',
            'title': 'How to convert webp to png free online',
            'description': 'How to convert your webp images to png format for free online',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-tiff',
            'title': 'How to convert bmp to tiff free online',
            'description': 'How to convert your bmp images to tiff format for free online',
            'image': 'bmp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-jpg',
            'title': 'How to convert webp to jpg free online',
            'description': 'How to convert your webp images to jpg format for free online',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-jpg',
            'title': 'How to convert png to jpg free online',
            'description': 'How to convert your png images to jpg format for free online',
            'image': 'png-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-webp',
            'title': 'How to convert bitmap/bmp to WEBP free online',
            'description': 'How to convert your bitmap images to WEBP format for free online',
            'image': 'bmp-to-webp-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-bmp',
            'title': 'How to convert png to bmp free online',
            'description': 'How to convert your png images to bmp format for free online',
            'image': 'png-to-bmp-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-tiff',
            'title': 'How to convert png to tiff free online',
            'description': 'How to convert your png images to tiff format for free online',
            'image': 'png-to-tiff-blog.svg',
        },  
        {
            'slug': 'how-to-convert-image-from-webp-to-bmp',
            'title': 'How to convert webp to bmp free online',
            'description': 'How to convert your webp images to bmp format for free online',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-webp',
            'title': 'How to convert png to webp free online',
            'description': 'How to convert your png images to webp format for free online',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-tiff-to-jpg',
            'title': 'How to convert tiff to jpg free online',
            'description': 'How to convert your tiff images to jpg format for free online',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-jpg-to-webp',
            'title': 'How to convert jpg to webp free online',
            'description': 'How to convert your jpg images to webp format for free online',
            'image': 'webp-to-jpg-blog.svg',
        }, 
        {
            'slug': 'how-to-reduce-the-size-of-images-using-image-size-reducer',
            'title': 'How to reduce the size of images free online',
            'description': 'Efficiently reduce the size of your images using an efficient tool for image size reducer',
            'image': 'image-size-reducer-blog.svg',
        },   
        {
            'slug': 'how-to-convert-image-from-jpg-to-jpeg',
            'title': 'How to convert JPG to JPEG free online',
            'description': 'How to convert your JPG images to JPEG format for free online',
            'image': 'jpeg-to-jpg-blog.svg',
        },   
        {
            'slug': 'how-to-convert-image-from-jpg-to-ico',
            'title': 'How to convert JPG to ICO free online',
            'description': 'How to convert your JPG images to ICO format for free online',
            'image': 'jpg-to-ico-blog.svg',
        }, 
        {
            'slug': 'how-to-convert-image-from-bmp-to-jpg',
            'title': 'How to convert bmp to jpg free online',
            'description': 'How to convert your bmp images to jpg format for free online',
            'image': 'bmp-to-png-blog.svg',
        },  
        {
            'slug': 'how-to-rotate-images-online-for-free',
            'title': 'How to rotate images free online',
            'description': 'How to rotate images images for free online',
            'image': 'image-rotate-blog.svg',
        }, 
        {
            'slug': 'how-to-crop-images-online-for-free',
            'title': 'How to crop images free online',
            'description': 'How to crop images images for free online',
            'image': 'crop-image-blog.svg',
        },  
        {
            'slug': 'how-to-convert-image-from-jpeg-to-png',
            'title': 'How to convert jpeg to png free online',
            'description': 'How to convert your jpeg images to png format for free online',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-jpeg-to-webp',
            'title': 'How to convert jpeg to webp free online',
            'description': 'How to convert your jpeg images to webp format for free online',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'best-tools-to-blur-faces-in-photos',
            'title': 'Top 3 tools to blur faces or any area in photos',
            'description': 'Top 3 tools to blur faces or any area in photos online for free.',
            'image': 'best-blur-face-tools-blog.svg',
        },

    ],
    'hi': [
        {
            'slug': 'jpeg-ko-jpg-me-kaise-badlein',
            'title': 'JPEG को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPEG चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'chhavi-me-chehre-ko-kaise-dhundhla-karen',
            'title': 'छवियों में चेहरे पर धुंधला प्रभाव कैसे लागू करें',
            'description': 'ऑनलाइन मुफ्त में छवियों में चेहरे पर धुंधला प्रभाव लागू करने का तरीका जानें',
            'image': 'blur-face-blog.svg',
        },
        {
            'slug': 'bmp-ko-jpeg-me-kaise-badlein',
            'title': 'Bitmap/BMP को JPEG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने bitmap चित्रों को JPEG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bitmap-to-jpeg-blog.svg',
        },
        {
            'slug': 'webp-ko-tiff-me-kaise-badlein',
            'title': 'WEBP को TIFF में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को TIFF प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'webp-ko-jpeg-me-kaise-badlein',
            'title': 'WEBP को JPEG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को JPEG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'bmp-ko-png-me-kaise-badlein',
            'title': 'BMP को PNG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने BMP चित्रों को PNG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'webp-ko-png-me-kaise-badlein',
            'title': 'WEBP को PNG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को PNG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'bmp-ko-tiff-me-kaise-badlein',
            'title': 'BMP को TIFF में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने BMP चित्रों को TIFF प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-tiff-blog.svg',
        },
        {
            'slug': 'webp-ko-jpg-me-kaise-badlein',
            'title': 'WEBP को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'png-ko-jpg-me-kaise-badlein',
            'title': 'PNG को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'png-to-jpg-blog.svg',
        },
        {
            'slug': 'bmp-ko-webp-me-kaise-badlein',
            'title': 'Bitmap/BMP को WEBP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने bitmap चित्रों को WEBP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'png-ko-bmp-me-kaise-badlein',
            'title': 'PNG को BMP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को BMP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'png-to-bmp-blog.svg',
        },
        {
            'slug': 'png-ko-tiff-me-kaise-badlein',
            'title': 'PNG को TIFF में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को TIFF प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'png-to-tiff-blog.svg',
        },
        {
            'slug': 'webp-ko-bmp-me-kaise-badlein',
            'title': 'WEBP को BMP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को BMP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'png-ko-webp-me-kaise-badlein',
            'title': 'PNG को WEBP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को WEBP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'tiff-ko-jpg-me-kaise-badlein',
            'title': 'TIFF को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने TIFF चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'jpg-ko-webp-me-kaise-badlein',
            'title': 'JPG को WEBP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPG चित्रों को WEBP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'chhavi-ka-size-kaise-kam-karen',
            'title': 'छवियों का आकार मुफ्त में ऑनलाइन कैसे कम करें',
            'description': 'छवियों के आकार को कम करने के लिए एक प्रभावी उपकरण का उपयोग करके अपने चित्रों का आकार कुशलता से कम करें',
            'image': 'image-size-reducer-blog.svg',
        },
        {
            'slug': 'jpg-ko-jpeg-me-kaise-badlein',
            'title': 'JPG को JPEG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPG चित्रों को JPEG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'jpg-ko-ico-me-kaise-badlein',
            'title': 'JPG को ICO में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPG चित्रों को ICO प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'jpg-to-ico-blog.svg',
        },
        {
            'slug': 'bmp-ko-jpg-me-kaise-badlein',
            'title': 'बीएमपी को जेपीजी में मुफ्त ऑनलाइन कैसे बदलें',
            'description': 'अपनी बीएमपी छवियों को मुफ्त में ऑनलाइन जेपीजी प्रारूप में कैसे बदलें',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'chhavi-ko-kaise-ghumayen',
            'title': 'मुफ्त में छवियों को ऑनलाइन कैसे घुमाएं',
            'description': 'मुफ्त में छवियों को ऑनलाइन कैसे घुमाएं',
            'image': 'image-rotate-blog.svg',
        },
        {
            'slug': 'chhavi-ko-kaise-crop-karen',
            'title': 'ऑनलाइन इमेज कैसे क्रॉप करें मुफ्त में',
            'description': 'इमेज को मुफ्त में ऑनलाइन कैसे क्रॉप करें',
            'image': 'crop-image-blog.svg',
        },
        {
            'slug': 'jpeg-ko-png-me-kaise-badlein',
            'title': 'JPEG को PNG में मुफ्त ऑनलाइन कैसे बदलें',
            'description': 'अपने JPEG इमेज को मुफ्त में ऑनलाइन PNG फॉर्मेट में कैसे बदलें',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'jpeg-ko-webp-me-kaise-badlein',
            'title': "JPEG को WEBP में मुफ्त ऑनलाइन कैसे बदलें",
            'description': "अपने JPEG चित्रों को मुफ्त ऑनलाइन WEBP प्रारूप में कैसे बदलें",
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'chhavi-me-chehre-ko-kaise-dhundhla-karen',
            'title': 'फोटो में चेहरा या कोई भी क्षेत्र धुंधला करने के लिए टॉप 3 टूल्स',
            'description': 'फोटो में चेहरा या कोई भी क्षेत्र ऑनलाइन मुफ्त में धुंधला करने के लिए टॉप 3 टूल्स।',
            'image': 'best-blur-face-tools-blog.svg',
        }

    ],
    'fr': [
        {
            'slug': 'comment-convertir-image-de-jpeg-a-jpg',
            'title': 'Comment convertir JPEG en JPG gratuitement en ligne',
            'description': 'Comment convertir vos images JPEG au format JPG gratuitement en ligne',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'comment-flouter-visage-sur-images-en-ligne',
            'title': 'Comment appliquer un flou sur le visage dans les images',
            'description': 'Découvrez comment appliquer un effet de flou sur le visage dans les images en ligne gratuitement',
            'image': 'blur-face-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-bmp-a-jpeg',
            'title': 'Comment convertir bitmap/bmp en JPEG gratuitement en ligne',
            'description': 'Comment convertir vos images bitmap au format JPEG gratuitement en ligne',
            'image': 'bitmap-to-jpeg-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-webp-a-tiff',
            'title': 'Comment convertir webp en tiff gratuitement en ligne',
            'description': 'Comment convertir vos images webp au format tiff gratuitement en ligne',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-webp-a-jpeg',
            'title': 'Comment convertir webp en jpeg gratuitement en ligne',
            'description': 'Comment convertir vos images webp au format jpeg gratuitement en ligne',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-bmp-a-png',
            'title': 'Comment convertir bmp en png gratuitement en ligne',
            'description': 'Comment convertir vos images bmp au format png gratuitement en ligne',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-webp-a-png',
            'title': 'Comment convertir webp en png gratuitement en ligne',
            'description': 'Comment convertir vos images webp au format png gratuitement en ligne',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-bmp-a-tiff',
            'title': 'Comment convertir bmp en tiff gratuitement en ligne',
            'description': 'Comment convertir vos images bmp au format tiff gratuitement en ligne',
            'image': 'bmp-to-tiff-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-webp-a-jpg',
            'title': 'Comment convertir webp en jpg gratuitement en ligne',
            'description': 'Comment convertir vos images webp au format jpg gratuitement en ligne',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-png-a-jpg',
            'title': 'Comment convertir png en jpg gratuitement en ligne',
            'description': 'Comment convertir vos images png au format jpg gratuitement en ligne',
            'image': 'png-to-jpg-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-bmp-a-webp',
            'title': 'Comment convertir bitmap/bmp en WEBP gratuitement en ligne',
            'description': 'Comment convertir vos images bitmap au format WEBP gratuitement en ligne',
            'image': 'bmp-to-webp-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-png-a-bmp',
            'title': 'Comment convertir png en bmp gratuitement en ligne',
            'description': 'Comment convertir vos images png au format bmp gratuitement en ligne',
            'image': 'png-to-bmp-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-png-a-tiff',
            'title': 'Comment convertir png en tiff gratuitement en ligne',
            'description': 'Comment convertir vos images png au format tiff gratuitement en ligne',
            'image': 'png-to-tiff-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-webp-a-bmp',
            'title': 'Comment convertir webp en bmp gratuitement en ligne',
            'description': 'Comment convertir vos images webp au format bmp gratuitement en ligne',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-png-a-webp',
            'title': 'Comment convertir png en webp gratuitement en ligne',
            'description': 'Comment convertir vos images png au format webp gratuitement en ligne',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-tiff-a-jpg',
            'title': 'Comment convertir tiff en jpg gratuitement en ligne',
            'description': 'Comment convertir vos images tiff au format jpg gratuitement en ligne',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-jpg-a-webp',
            'title': 'Comment convertir jpg en webp gratuitement en ligne',
            'description': 'Comment convertir vos images jpg au format webp gratuitement en ligne',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'comment-reduire-taille-d-images-en-ligne',
            'title': 'Comment réduire la taille des images gratuitement en ligne',
            'description': 'Réduisez efficacement la taille de vos images en utilisant un outil efficace pour réduire la taille des images',
            'image': 'image-size-reducer-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-jpg-a-jpeg',
            'title': 'Comment convertir JPG en JPEG gratuitement en ligne',
            'description': 'Comment convertir vos images JPG au format JPEG gratuitement en ligne',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-jpg-a-ico',
            'title': 'Comment convertir JPG en ICO gratuitement en ligne',
            'description': 'Comment convertir vos images JPG au format ICO gratuitement en ligne',
            'image': 'jpg-to-ico-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-bmp-a-jpg',
            'title': 'Comment convertir bmp en jpg gratuitement en ligne',
            'description': 'Comment convertir vos images bmp au format jpg gratuitement en ligne',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'comment-faire-pivoter-images-en-ligne',
            'title': 'Comment faire pivoter des images gratuitement en ligne',
            'description': 'Comment faire pivoter des images gratuitement en ligne',
            'image': 'image-rotate-blog.svg',
        },
        {
            'slug': 'comment-recadrer-images-en-ligne',
            'title': 'Comment recadrer des images gratuitement en ligne',
            'description': 'Comment recadrer des images gratuitement en ligne',
            'image': 'crop-image-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-jpeg-a-png',
            'title': 'Comment convertir JPEG en PNG gratuitement en ligne',
            'description': 'Comment convertir vos images JPEG au format PNG gratuitement en ligne',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'comment-convertir-image-de-jpeg-a-webp',
            'title': "Comment convertir JPEG en WEBP gratuitement en ligne",
            'description': "Comment convertir vos images JPEG au format WEBP gratuitement en ligne",
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'meilleurs-outils-pour-flouter-les-visages-ou-zones-dans-les-photos',
            'title': "Top 3 outils pour flouter les visages ou n'importe quelle zone dans les photos",
            'description': "Top 3 outils pour flouter les visages ou n'importe quelle zone dans les photos en ligne gratuitement.",
            'image': 'best-blur-face-tools-blog.svg',
        }

    ]
}