blogs_list = {
    'en': [
        {
            'slug': 'how-to-convert-image-from-jpeg-to-jpg',
            'title': 'How to convert JPEG to JPG free online',
            'description': 'How to convert your JPEG images to JPG format for free online',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-blur-face-on-images-online-for-free',
            'title': 'How to apply blur filter on face in images',
            'description': 'Discover how to apply blur effect on the face in images online for free',
            'image': 'blur-face-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-jpeg',
            'title': 'How to convert bitmap/bmp to JPEG free online',
            'description': 'How to convert your bitmap images to JPEG format for free online',
            'image': 'bitmap-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-tiff',
            'title': 'How to convert webp to tiff free online',
            'description': 'How to convert your webp images to tiff format for free online',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-jpeg',
            'title': 'How to convert webp to jpeg free online',
            'description': 'How to convert your webp images to jpeg format for free online',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-png',
            'title': 'How to convert bmp to png free online',
            'description': 'How to convert your bmp images to png format for free online',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-png',
            'title': 'How to convert webp to png free online',
            'description': 'How to convert your webp images to png format for free online',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-tiff',
            'title': 'How to convert bmp to tiff free online',
            'description': 'How to convert your bmp images to tiff format for free online',
            'image': 'bmp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-jpg',
            'title': 'How to convert webp to jpg free online',
            'description': 'How to convert your webp images to jpg format for free online',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-jpg',
            'title': 'How to convert png to jpg free online',
            'description': 'How to convert your png images to jpg format for free online',
            'image': 'png-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-webp',
            'title': 'How to convert bitmap/bmp to WEBP free online',
            'description': 'How to convert your bitmap images to WEBP format for free online',
            'image': 'bmp-to-webp-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-bmp',
            'title': 'How to convert png to bmp free online',
            'description': 'How to convert your png images to bmp format for free online',
            'image': 'png-to-bmp-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-tiff',
            'title': 'How to convert png to tiff free online',
            'description': 'How to convert your png images to tiff format for free online',
            'image': 'png-to-tiff-blog.svg',
        },  
        {
            'slug': 'how-to-convert-image-from-webp-to-bmp',
            'title': 'How to convert webp to bmp free online',
            'description': 'How to convert your webp images to bmp format for free online',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-webp',
            'title': 'How to convert png to webp free online',
            'description': 'How to convert your png images to webp format for free online',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-tiff-to-jpg',
            'title': 'How to convert tiff to jpg free online',
            'description': 'How to convert your tiff images to jpg format for free online',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-jpg-to-webp',
            'title': 'How to convert jpg to webp free online',
            'description': 'How to convert your jpg images to webp format for free online',
            'image': 'webp-to-jpg-blog.svg',
        }, 
        {
            'slug': 'how-to-reduce-the-size-of-images-using-image-size-reducer',
            'title': 'How to reduce the size of images free online',
            'description': 'Efficiently reduce the size of your images using an efficient tool for image size reducer',
            'image': 'image-size-reducer-blog.svg',
        },   
        {
            'slug': 'how-to-convert-image-from-jpg-to-jpeg',
            'title': 'How to convert JPG to JPEG free online',
            'description': 'How to convert your JPG images to JPEG format for free online',
            'image': 'jpeg-to-jpg-blog.svg',
        },   
        {
            'slug': 'how-to-convert-image-from-jpg-to-ico',
            'title': 'How to convert JPG to ICO free online',
            'description': 'How to convert your JPG images to ICO format for free online',
            'image': 'jpg-to-ico-blog.svg',
        }, 
        {
            'slug': 'how-to-convert-image-from-bmp-to-jpg',
            'title': 'How to convert bmp to jpg free online',
            'description': 'How to convert your bmp images to jpg format for free online',
            'image': 'bmp-to-png-blog.svg',
        },  
        {
            'slug': 'how-to-rotate-images-online-for-free',
            'title': 'How to rotate images free online',
            'description': 'How to rotate images images for free online',
            'image': 'image-rotate-blog.svg',
        },  
    ],
    'hi': [
        {
            'slug': 'how-to-convert-image-from-jpeg-to-jpg',
            'title': 'JPEG को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPEG चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-blur-face-on-images-online-for-free',
            'title': 'छवियों में चेहरे पर धुंधला प्रभाव कैसे लागू करें',
            'description': 'ऑनलाइन मुफ्त में छवियों में चेहरे पर धुंधला प्रभाव लागू करने का तरीका जानें',
            'image': 'blur-face-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-jpeg',
            'title': 'Bitmap/BMP को JPEG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने bitmap चित्रों को JPEG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bitmap-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-tiff',
            'title': 'WEBP को TIFF में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को TIFF प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-jpeg',
            'title': 'WEBP को JPEG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को JPEG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-png',
            'title': 'BMP को PNG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने BMP चित्रों को PNG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-png',
            'title': 'WEBP को PNG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को PNG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-tiff',
            'title': 'BMP को TIFF में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने BMP चित्रों को TIFF प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-jpg',
            'title': 'WEBP को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-jpg',
            'title': 'PNG को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'png-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-webp',
            'title': 'Bitmap/BMP को WEBP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने bitmap चित्रों को WEBP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-bmp',
            'title': 'PNG को BMP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को BMP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'png-to-bmp-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-tiff',
            'title': 'PNG को TIFF में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को TIFF प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'png-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-webp-to-bmp',
            'title': 'WEBP को BMP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने WEBP चित्रों को BMP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'bmp-to-png-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-png-to-webp',
            'title': 'PNG को WEBP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने PNG चित्रों को WEBP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpeg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-tiff-to-jpg',
            'title': 'TIFF को JPG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने TIFF चित्रों को JPG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-tiff-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-jpg-to-webp',
            'title': 'JPG को WEBP में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPG चित्रों को WEBP प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'webp-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-reduce-the-size-of-images-using-image-size-reducer',
            'title': 'छवियों का आकार मुफ्त में ऑनलाइन कैसे कम करें',
            'description': 'छवियों के आकार को कम करने के लिए एक प्रभावी उपकरण का उपयोग करके अपने चित्रों का आकार कुशलता से कम करें',
            'image': 'image-size-reducer-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-jpg-to-jpeg',
            'title': 'JPG को JPEG में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPG चित्रों को JPEG प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'jpeg-to-jpg-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-jpg-to-ico',
            'title': 'JPG को ICO में ऑनलाइन मुफ्त में कैसे बदलें',
            'description': 'कैसे अपने JPG चित्रों को ICO प्रारूप में मुफ्त में ऑनलाइन बदलें',
            'image': 'jpg-to-ico-blog.svg',
        },
        {
            'slug': 'how-to-convert-image-from-bmp-to-jpg',
            'title': 'बीएमपी को जेपीजी में मुफ्त ऑनलाइन कैसे बदलें',
            'description': 'अपनी बीएमपी छवियों को मुफ्त में ऑनलाइन जेपीजी प्रारूप में कैसे बदलें',
            'image': 'bmp-to-png-blog.svg',
        },  
        {
            'slug': 'how-to-rotate-images-online-for-free',
            'title': 'मुफ्त में छवियों को ऑनलाइन कैसे घुमाएं',
            'description': 'मुफ्त में छवियों को ऑनलाइन कैसे घुमाएं',
            'image': 'image-rotate-blog.svg',
        },
    ]
}